- name: Include Common Role for OS Prereqs
  include_role:
    name: common
    tasks_from: os

# - name: Include filebeat roles
#   include_role:
#     name: common
#     tasks_from: filebeat

#- name: Include Azure CLI roles
#  include_role:
#    name: common
#    tasks_from: az_cli

# - name: Include node exporter role
#   include_role:
#     name: common
#     tasks_from: node_exporter

# - name: Include rsyslog role
#   include_role:
#     name: common
#     tasks_from: rsyslog

- name: Install {{COMPONENT}}
  yum: 
    name: 
      - epel-release 
      - yum-utils
    state: present

- name: Add {{COMPONENT}} repository
  shell: |
    yum install "{{REDIS_REPO}}" -y
    yum-config-manager --enable remi
    yum install redis -y

- name: Update the BindIP in redif conf
  replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting {{COMPONENT}} services
  systemd: 
   daemon_reload: yes
   enabled: yes
   state: restarted
   name: redis

