- name: Include Common Role for OS Prereqs
  include_role:
    name: common
    tasks_from: os
   
- name: Include Common Role for OS Prereqs
  include_role:
    name: common
    tasks_from: os

- name: Installing Redis Repo and Server
  yum:
    name:
    - {{REDIS_REPO}}
    - redis
    state: latest
    enablerepo: remi

# yum install epel-release yum-utils -y &>>$LOG_FILE

- name: Configuring redis.conf file
  replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting {{COMPONENT}} services
  systemd: 
   daemon_reload: yes
   enabled: yes
   state: restarted
   name: redis

