- name: Include Common Role for OS Prereqs
  include_role:
    name: common
    tasks_from: os

- name: Adding Repo files
  yum: 
    name: "{{REDIS_REPO}}"
    state: present

- name: Installing Redis Server
  yum:
    name:
      - redis
      - epel-release 
      - yum-utils
    state: latest
    enablerepo: remi

- name: Configuring redis.conf file
  replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting {{COMPONENT}} services
  systemd: 
   daemon_reload: yes
   enabled: yes
   state: restarted
   name: redis

