- name: Include Common Role
  include_role:
    name: common
    tasks_from: nodejs

- name: Include Prometheus Role
  include_role:
    name: prometheus

- name: Include Filebeat Role
  include_role:
    name: filebeat
