- name: Include Common Role for OS Prereqs
  include_role:
    name: common
    tasks_from: os

- name: Include filebeat roles
  include_role:
    name: common
    tasks_from: filebeat

- name: Include Azure CLI roles
  include_role:
    name: common
    tasks_from: az_cli

- name: Include node exporter role
  include_role:
    name: common
    tasks_from: node_exporter

- name: Include rsyslog role
  include_role:
    name: common
    tasks_from: rsyslog

- name: Install NodeJs
  include_role:
    name: common
    tasks_from: nodejs

- name: Add App user
  user:
    name: roboshop
    comment: RoboShop user

- name: Make App Directory
  file:
    path: /home/roboshop/user
    state: directory

- name: Copy Component files to App Directory
  copy: 
    src: files/
    dest: /home/roboshop/user

- name: Add {{COMPONENT}} service file
  template:
    src: user.service
    dest: /etc/systemd/system/user.service

- name: Installing NPM dependencies
  include_role:
    name: common
    tasks_from: npm

- name: Enamble/Start {{COMPONENT}} services
  systemd:
    daemon_reload: yes
    enabled: yes
    name: user
    state: restarted 