- name: Include Common Role for OS Prereqs
  include_role:
    name: common
    tasks_from: os
   
- name: Installing required packages
  yum:
    name: 
      - python36 
      - gcc 
      - python3-devel
    state: latest
    
- name: User App user
  user:
    name: roboshop
    comment: RoboShop user

- name: Make {{COMPONENT}} Directory
  file:
    path: /home/roboshop/{{COMPONENT}}
    state: directory

- name: Download Repo files
  copy:
    src: files/
    dest: /home/roboshop/{{COMPONENT}}

# - name: Install Python Packages with requirements.txt file
#   shell: |
#     cd /home/roboshop/{{COMPONENT}}
#     pip3 install -r requirements.txt

- name: Install Python Packages with requirements.txt file
  pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt

- name: Update the roboshop user and group id in payment.ini file
  template:
   src: payment.service 
   dest: /etc/systemd/system/payment.service

- name: Start Payment Services
  systemd:
   daemon_reload: yes
   enabled: yes
   state: restarted
   name: payment 