- name: Include Common Role for OS Prereqs
  include_role:
    name: common
    tasks_from: os

- name: Install NGINX
  yum: 
    name: nginx
    state: present

- name: Delete content from /usr/share/nginx/html
  file:
    state: absent
    path: /usr/share/nginx/html

- name: Create content from /usr/share/nginx/html
  file:
    state: directory
    path: /usr/share/nginx/html

- name: Copy the HTDOCS content and deploy under the Nginx path
  copy:
    src: /*
    dest: /usr/share/nginx/html

- name: Setup /etc/nginx/default.d/roboshop.conf
  template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Update Nginx Configuration
  template:
   src: nginx.conf
   dest: /etc/nginx/nginx.conf

- name: Starting nginx services
  systemd: 
   daemon_reload: yes
   enabled: yes
   state: restarted
   name: nginx
  ignore_errors: yes

