- name: Installing erlang package
  shell: |
    yum install {{Erlang}} -y

- name: Adding RabbitMQ Repo
  shell: |
    curl -s {{RabbitMQ_Repository}} | sudo bash

- name: Installing RabbitMQ Server
  yum: 
    name: rabbitmq-server
    state: latest

- name: Adding RabbitMQ user for Application
  shell: |
    rabbitmqctl add_user roboshop roboshop123
    rabbitmqctl set_user_tags roboshop administrator
    rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

- name: Start RabbitMQ service
  systemd:
    daemon_reload: yes
    name: rabbitmq-server
    state: started
    enabled: yes

