- name: Include Common Role for OS Prereqs
  include_role:
    name: common
    tasks_from: os

- name: Include filebeat roles
  include_role:
    name: common
    tasks_from: filebeat

- name: Include Azure CLI roles
  include_role:
    name: common
    tasks_from: az_cli

- name: Include node exporter role
  include_role:
    name: common
    tasks_from: node_exporter

- name: Include rsyslog role
  include_role:
    name: common
    tasks_from: rsyslog

# - name: Include Python Role for Payment
#   include_role:
#     name: common
#     tasks_from: python

- name: Install Python modules 
  shell: yum install python36 gcc python3-devel -y

- name: User App user
  user:
    name: roboshop
    comment: RoboShop user

- name: Make {{COMPONENT}} Directory
  file:
    path: /home/roboshop/{{COMPONENT}}
    state: directory

- name: Download Repo files
  copy:
    src: files/
    dest: /home/roboshop/{{COMPONENT}}

- name: Install Python Packages
  shell: cd /home/roboshop/{{COMPONENT}} ; pip3 install -r requirements.txt

# - name: Install Python Packages
#   pip:
#    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
#   executable: pip-3

- name: Update the roboshop user and group id in payment.ini file
  template:
   src: payment.service 
   dest: /etc/systemd/system/payment.service

- name: Start Payment Services
  systemd:
   daemon_reload: yes
   enabled: yes
   state: restarted
   name: payment 