- name: Include Common Role for Python
  include_role:
    name: common
    tasks_from: python

- name: Include Prometheus Role
  include_role:
    name: prometheus

- name: Include Filebeat Role
  include_role:
    name: filebeat
