- name: Install Filebeat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.10.2-x86_64.rpm
    state: present

- name: Update Filebeat Configuration
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

- name: Restart Filebeat Service
  systemd:
    name: filebeat
    state: restarted
    enabled: yes

