- name: Include Common Role for Java
  include_role:
    name: common
    tasks_from: java

- name: Include Prometheus Role
  include_role:
    name: prometheus

- name: Include Filebeat Role
  include_role:
    name: filebeat
