- name: Include Common Role for OS Prereqs
  include_role:
    name: common
    tasks_from: os

- name: Include filebeat roles
  include_role:
    name: common
    tasks_from: filebeat

#- name: Include Azure CLI roles
#  include_role:
#    name: common
#    tasks_from: az_cli

- name: Include node exporter role
  include_role:
    name: common
    tasks_from: node_exporter

- name: Include rsyslog role
  include_role:
    name: common
    tasks_from: rsyslog

- name: Install NodeJS tools
  include_role:
    name: common
    tasks_from: nodejs

- name: Create Application User
  user:
    name: roboshop
    comment: Robo Shop

- name: Make {{COMPONENT}} Folder
  file:
    path: /home/roboshop/{{COMPONENT}}
    state: directory

- name: Download and Extract Artifacts
  copy:
   src: files/
   dest: /home/roboshop/{{COMPONENT}}

- name: Installing NodeJS dependencies
  include_role:
    name: common
    tasks_from: npm
  
- name: Add cart.service file
  template:
   src: cart.service
   dest: /etc/systemd/system/cart.service
   
- name: Starting cart services
  systemd: 
   daemon_reload: yes
   enabled: yes
   state: restarted
   name: cart
